//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed_Market.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursed_Market.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLOODWEB LEVEL.
        /// </summary>
        internal static string CHARACTERSPRESET_BloodWebTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_BloodWebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT CHARACTER.
        /// </summary>
        internal static string CHARACTERSPRESET_CharacterSelectTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_CharacterSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CONFIGURE CHARACTERS PRESET.
        /// </summary>
        internal static string CHARACTERSPRESET_CharactersPresetTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_CharactersPresetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EXTRA ACTIONS.
        /// </summary>
        internal static string CHARACTERSPRESET_ExtraActionsTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_ExtraActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LEGACY PRESTIGE LEVEL.
        /// </summary>
        internal static string CHARACTERSPRESET_LegacyPrestigeTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_LegacyPrestigeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PRESTIGE LEVEL.
        /// </summary>
        internal static string CHARACTERSPRESET_PrestigeTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_PrestigeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Randomize all characters presets.
        /// </summary>
        internal static string CHARACTERSPRESET_RandomizePresets {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_RandomizePresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm and Save Changes.
        /// </summary>
        internal static string CHARACTERSPRESET_SaveChanges {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spread current preset among all characters.
        /// </summary>
        internal static string CHARACTERSPRESET_SpreadPreset {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_SpreadPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cloud-ID to Send a Friend Request to.
        /// </summary>
        internal static string FRIEND_FriendCloudIDTitle {
            get {
                return ResourceManager.GetString("FRIEND_FriendCloudIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Cloud-ID.
        /// </summary>
        internal static string FRIEND_MyCloudIDTitle {
            get {
                return ResourceManager.GetString("FRIEND_MyCloudIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CLOUD-ID FRIEND REQUEST.
        /// </summary>
        internal static string FRIEND_Title {
            get {
                return ResourceManager.GetString("FRIEND_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s rock! 🤘.
        /// </summary>
        internal static string GREETINGS_01 {
            get {
                return ResourceManager.GetString("GREETINGS_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How&apos;s your day been?.
        /// </summary>
        internal static string GREETINGS_02 {
            get {
                return ResourceManager.GetString("GREETINGS_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s groove! 🕺.
        /// </summary>
        internal static string GREETINGS_03 {
            get {
                return ResourceManager.GetString("GREETINGS_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gaming Time! ⚔.
        /// </summary>
        internal static string GREETINGS_04 {
            get {
                return ResourceManager.GetString("GREETINGS_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time to groove! 🎵.
        /// </summary>
        internal static string GREETINGS_05 {
            get {
                return ResourceManager.GetString("GREETINGS_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Another day, another challenge!.
        /// </summary>
        internal static string GREETINGS_06 {
            get {
                return ResourceManager.GetString("GREETINGS_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s roll! 🎲.
        /// </summary>
        internal static string GREETINGS_07 {
            get {
                return ResourceManager.GetString("GREETINGS_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time to shine! ✨.
        /// </summary>
        internal static string GREETINGS_08 {
            get {
                return ResourceManager.GetString("GREETINGS_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From time to time, some ingame items may appear to be bugged, so developers turn them off. This restriction has now been removed..
        /// </summary>
        internal static string MAIN_AntiKillSwitchDescription {
            get {
                return ResourceManager.GetString("MAIN_AntiKillSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KillSwitch Remover Status:  .
        /// </summary>
        internal static string MAIN_AntiKillSwitchTitle {
            get {
                return ResourceManager.GetString("MAIN_AntiKillSwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bhvrSession will be shown here....
        /// </summary>
        internal static string MAIN_BhvrSession {
            get {
                return ResourceManager.GetString("MAIN_BhvrSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CROSSHAIR OPACITY.
        /// </summary>
        internal static string MAIN_CrosshairOpacityTitle {
            get {
                return ResourceManager.GetString("MAIN_CrosshairOpacityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CROSSHAIR.
        /// </summary>
        internal static string MAIN_CrosshairTitle {
            get {
                return ResourceManager.GetString("MAIN_CrosshairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CURRENCIES AMOUNTS.
        /// </summary>
        internal static string MAIN_CurrenciesAdjustTitle {
            get {
                return ResourceManager.GetString("MAIN_CurrenciesAdjustTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some customization sets were designed so they only show up and release at the very specific date. This restriction has now been removed..
        /// </summary>
        internal static string MAIN_CustomizationsKingDescription {
            get {
                return ResourceManager.GetString("MAIN_CustomizationsKingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customizations King Status:  .
        /// </summary>
        internal static string MAIN_CustomizationsKingTitle {
            get {
                return ResourceManager.GetString("MAIN_CustomizationsKingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currently In Use.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_CurrentlyInUse {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_CurrentlyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_Disabled {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed To Obtain.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_FailedToObtain {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_FailedToObtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OFFLINE MODE.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_Offline {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GAME CHANGERS.
        /// </summary>
        internal static string MAIN_GameChangersTitle {
            get {
                return ResourceManager.GetString("MAIN_GameChangersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queue Position Overlay.
        /// </summary>
        internal static string MAIN_MainCheckBox_01 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjust Currencies Amount (Visual).
        /// </summary>
        internal static string MAIN_MainCheckBox_02 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable Temporary SaveFile.
        /// </summary>
        internal static string MAIN_MainCheckBox_03 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Characters Preset.
        /// </summary>
        internal static string MAIN_MainCheckBox_04 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Game Changers.
        /// </summary>
        internal static string MAIN_MainCheckBox_05 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only Unlock DLC&apos;s.
        /// </summary>
        internal static string MAIN_MainCheckBox_06 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Guaranteed Quest Completion.
        /// </summary>
        internal static string MAIN_MainCheckBox_07 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAIN FEATURES.
        /// </summary>
        internal static string MAIN_MainFeaturesTitle {
            get {
                return ResourceManager.GetString("MAIN_MainFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string MAIN_NOTIFYICON_Close {
            get {
                return ResourceManager.GetString("MAIN_NOTIFYICON_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show.
        /// </summary>
        internal static string MAIN_NOTIFYICON_Show {
            get {
                return ResourceManager.GetString("MAIN_NOTIFYICON_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LOBBY FOUND....
        /// </summary>
        internal static string MAIN_QUEUE_LobbyFound {
            get {
                return ResourceManager.GetString("MAIN_QUEUE_LobbyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATCH STARTING!.
        /// </summary>
        internal static string MAIN_QUEUE_MatchStarting {
            get {
                return ResourceManager.GetString("MAIN_QUEUE_MatchStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на QUEUE POSITION:.
        /// </summary>
        internal static string MAIN_QUEUE_QueuePosition {
            get {
                return ResourceManager.GetString("MAIN_QUEUE_QueuePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на START.
        /// </summary>
        internal static string MAIN_Start {
            get {
                return ResourceManager.GetString("MAIN_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes were made to the character preset, but they were not saved. Do you want to close the window without saving?.
        /// </summary>
        internal static string MESSAGE_CharactersPresetUnsavedChanges {
            get {
                return ResourceManager.GetString("MESSAGE_CharactersPresetUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cursed Market failed to create data folder in %localappdata%! Please, verify that program is running with administrator privileges..
        /// </summary>
        internal static string MESSAGE_DataFolderCreationFailed {
            get {
                return ResourceManager.GetString("MESSAGE_DataFolderCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to read &quot;charactersPreset.json&quot; file! Make sure that file isn&apos;t empty and it&apos;s content is in JSON format..
        /// </summary>
        internal static string MESSAGE_FailedToReadCharactersPreset {
            get {
                return ResourceManager.GetString("MESSAGE_FailedToReadCharactersPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to Cursed Market!
        ///
        ///This software is Open-Source and Free To Use! In case you&apos;ve been convinced into paying for it, it&apos;s recommended to send seller a complaint..
        /// </summary>
        internal static string MESSAGE_FirstLaunch {
            get {
                return ResourceManager.GetString("MESSAGE_FirstLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cursed Market was designed with &quot;Roboto-Regular&quot; font in mind!
        ///
        ///Software won&apos;t work properly until the font is installed: &quot;{0}&quot;.
        /// </summary>
        internal static string MESSAGE_RobotoFontMissing {
            get {
                return ResourceManager.GetString("MESSAGE_RobotoFontMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на QUEUE POSITION WILL BE SHOWN HERE.
        /// </summary>
        internal static string QUEUE_Idle {
            get {
                return ResourceManager.GetString("QUEUE_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ~ LOBBY FOUND ~.
        /// </summary>
        internal static string QUEUE_LobbyFound {
            get {
                return ResourceManager.GetString("QUEUE_LobbyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATCH STARTING!.
        /// </summary>
        internal static string QUEUE_MatchStarting {
            get {
                return ResourceManager.GetString("QUEUE_MatchStarting", resourceCulture);
            }
        }
    }
}
