//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed_Market.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OfflineAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OfflineAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursed_Market.Properties.OfflineAPI", typeof(OfflineAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJytXVl34jrW/S95vg+VpOpObwEyVYUKN1DJuv2tXlkCC3DHtmgPSVG9+r/3PrINhqSkLfI9MO9jGR0NR2f8z9E0MSZ60NMb/ayT/lJlCx0d/TlXSaF/OapWkSp19KCSRJfF0Z//989fjmZLlatZqfOvKtVHfx4d/bJ7jaM/Tz/8crTKdVHGC918hW9a0ECV6ujP/xytVLmUSx59eDz+cIyryOtJ83ravH5sXj81r7/iFegGiecGi+cGjecGj+cNxa9NG0J70nnXXuWkuYq8q69yinf1VeRdfZWPePfb5t3vTRsnH/5o3x1/aFo7Oa7bkHfSBtpsWsNz0xqem9bw3LSG56Y1PDet4blpDc9Na3huWsNz0xqe29aOpQ357hTtntp28Yx30i6e8U7axTPeSbt4xjtpF894J+3iGe+kXTzjnbSL58dT2y6e8c62gXZPbbt4Bu74CKMkj7NFzen/+89RZiK98+EaQwxDoigxujCE+gbjC0MqOvrvP//7yx5+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BloodWebData {
            get {
                return ResourceManager.GetString("BloodWebData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJylfVlz20jS7X/xcz/Ykttu95vWxaIsNklJ0TMxoQDJIokmCHCwSKK/mP9+8xRQ2ChnZvE+cEcSQGUtWbmc838fojDLP/z57//7MFsFaTDLTfoj2JgPf364DaPIpB+/fvjtQ2SWwWw3TE2Wh0szMC8m+vDnx98akZvcbDL7LyG9u5mTOL56HkdBtjLp8+3x12HyalL6r/8WQZyH+e7Dn79//N9vvxb4QylQpC/hS5I+nwVRsAnS8CyJ82ATxkEeJvEJSc6T3HB/cxmmZhHtBvSzSWPxhGfBZksXeIkLjcLlKn8eBfE82WgF78z8NvQVmiRJNE3ePKVuzc734oKtVsJp6mqVZLmnco+0yq0EhlGwLIyfzFmUBOtTE0VqicHl2SoI4yx49biT33VXNaAxFefUNxfhskht31Sf5K8gD9JyNPoOos++At88BT5/9D2DssEagWOdgOvzx8eTIk1Nrj7DdZDPVh7H3x573/OR5y0cXWy2+r8P4mSaeHRZZaeo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterData {
            get {
                return ResourceManager.GetString("CharacterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJwtkk9v1DAQxb/LnjmUTezAsX+gaF8pRTkgQBzcrTdrNetU2YSKb1/PzxxiW3bezPvNzO+N0jjG+aLbvNtoe1HWvtmyNtw4Oy/xb+TuY1k/zWlftvs0HJdTmO3hfp3Ptl/FMJftYQzDiuAYXti33tbWQvaNJbk9TuflEPaopkfuP5T1Lg5pykjMUd+2uLDz9zXmJdmb8HYdck6PYbT8Ie//8btZV2Oiy/MRqZ2/5cTZ7D+kgT/NhQBSY+5u4mkapnmo2VvjFpbUWPb7KZvXm1fDLoev0cJcj2F9istiT9fHdf88xnM5fik1vSqfefqRlr052YVnShWDmavg5RdLdpp4+rmay8uncLLLlzQnS/Q5Zsu0C+RX855a0RZ891sz2W9ru+xVofoZp9daSSvKrzCnbKlv13weUx6idUpVTFDVoK2d78I6J/LVzlE5/R8MRoUu9lS6Z0iEg108HLiqfUPQ1ubXfpKvtXC9I4QDyPGnY0AcQR1uHFqH1qF1aD1a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharactersList {
            get {
                return ResourceManager.GetString("CharactersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJyNfV1327jO7n+Z633Rpp2ZPe9dbOejTdJ4YrdZs8/ay4u2aFs7suitj6buWee/vw9AUQQkOnMubAsARYIkCIIgSP/fX462eql/+Z//88vi46/zd+9/+Yd/uAgPH/Bw9+GfnsQPROIHT/o9kPDgSXgg0tJsmnyTm3JSmLp5yEu7mprCHEyVS+pzXtmlOUraxDaNrZZuZ5u9rYC4zn+YxmZ4+lSWtlo0lS13zZ54vPjYcU0PzDU9UPmLD+87Ej0wiR486SKQ8OBJeGCSK/IMbDQnAHOX11zsrTXZY8m5/xHKw4MvDw/85kXXFPzgSV1T3Lebl9OksuYFwGV5erCmrL/Yja1rU1FBTHNtg8cZiro1FZX6xT3kXQs828reuLI09/l3e+0q+53Ri4vfQpl48GXiwdcx9Cc9+Dp2/bn4ECpBD57UVeK6yI/XhTsST2C6sF/pcbm3D+iTwj5uHww1w8SsT3VOvQRgSv1mMlvllrKyG1dmz3lJNbgLbcIPLB6h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsList {
            get {
                return ResourceManager.GetString("ItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJylXF1z2zgS/CspPd1VpbZI6oNU3iQ5iR3Zjm6tteru6orFWEjEs0T6KDpe3db+9x3ZAkk0yGQGftCLJDSBwWDQ6Bnwj97XdKuWhwfVe9e7Sop7Vb75QN+8+dvZ5ezvvbe9u0IlZZpnZ0l5/Esw/sXzfwm8YPjG998NQvrHQ5F/T9eqoF9nj8Verd+ccCaLC/o5zb6rrMyLw0Wpdvveu3//0dsm+/K3hzUhTsreOz/sR/7Q96LobS//8l91V16sCessPlfJ2vMJ4n+PSVam5YH+++fb9ube2Atam8cLPoTfNyE+aIxLNojvewDyghFw+zAetDXvM5uHYdg6hAH38aE5CctVvOL23fcG5tDP0+32C30O8aX6tudbcIAmWObFPue3D9ETTu35ruD7I8sVNAjfF7yooydcg/oBzKZuH8+Soszz7F/sjuDaegFiu9W4wxz9mG1SL/A7MbirI4ws964wuGOJRsN2jEE8We+myabIc7ZZYH5rqOVTWt5tuKYZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarketDLC {
            get {
                return ResourceManager.GetString("MarketDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJyt/emPHEe25Yv+K43z6T3gosHkkEN/o4Yq1aGmI7KKt/vhIZFHzJL4RCXrJqnSUT/c//26e7iZm69t2/lblhVABAIRsVe427BtT8P//9/+/vbd7as//nH7b//j3765uf/l9uN/+9P0yX/7f/3pt3fv/t//9n/824/3tzcf376/++Lm4/ybx8/++6Mn//3xo8fn/+3Rxf84u5p+8Y/79/98++b2fvr289/uP9y++W8r0PPv/zJ9/fbun7d3H9/f//GXj7e/fvi3//H/+f//27ubDx//+o83E+Lzj//2P84uLp4+ffzk0dPH/8e/vf/P/9/tjx//8mbC+uL6q9ubN4/OJoj/67ebu49vP/4x/fb//j/65I8vzq+65NffY4jLR8/2EH8qGF9zkPOnj3rX8ZjexpPuKDxh5E8eXcoorLfwFP791dXTHf2r19ev6bU/eXS1v/av3r5795/T84/rr29/+sBn8umFDMGr9/cf3mP6q8uzPr2xFM7Pz3UcC4ix [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarketFull {
            get {
                return ResourceManager.GetString("MarketFull", resourceCulture);
            }
        }
    }
}
